In [ ]:
%matplotlib inline


Gaussian HMM of stock data
--------------------------

This script shows how to use Gaussian HMM on stock price data from
Yahoo! finance. For more information on how to visualize stock prices
with matplotlib, please refer to ``date_demo1.py`` of matplotlib.



In [2]:
from __future__ import print_function

import datetime

import numpy as np
from matplotlib import cm, pyplot as plt
from matplotlib.dates import YearLocator, MonthLocator
try:
    from matplotlib.finance import quotes_historical_yahoo_ochl
except ImportError:
    # For Matplotlib prior to 1.5.
    from matplotlib.finance import (
        quotes_historical_yahoo as quotes_historical_yahoo_ochl
    )

from hmmlearn.hmm import GaussianHMM


print(__doc__)

Automatically created module for IPython interactive environment


Get quotes from Yahoo! finance



In [5]:
quotes = quotes_historical_yahoo_ochl(
    "INTC", datetime.date(1995, 1, 1), datetime.date(2012, 1, 6))

# Unpack quotes
dates = np.array([q[0] for q in quotes], dtype=int)
close_v = np.array([q[2] for q in quotes])
volume = np.array([q[5] for q in quotes])[1:]

# Take diff of close value. Note that this makes
# ``len(diff) = len(close_t) - 1``, therefore, other quantities also
# need to be shifted by 1.
diff = np.diff(close_v)
dates = dates[1:]
close_v = close_v[1:]

# Pack diff and volume for training.
X = np.column_stack([diff, volume])

Run Gaussian HMM



In [6]:
print("fitting to HMM and decoding ...", end="")

# Make an HMM instance and execute fit
model = GaussianHMM(n_components=4, covariance_type="diag", n_iter=1000).fit(X)

# Predict the optimal sequence of internal hidden state
hidden_states = model.predict(X)

print("done")

fitting to HMM and decoding ...done


Print trained parameters and plot



In [ ]:
print("Transition matrix")
print(model.transmat_)
print()

print("Means and vars of each hidden state")
for i in range(model.n_components):
    print("{0}th hidden state".format(i))
    print("mean = ", model.means_[i])
    print("var = ", np.diag(model.covars_[i]))
    print()

fig, axs = plt.subplots(model.n_components, sharex=True, sharey=True)
colours = cm.rainbow(np.linspace(0, 1, model.n_components))
for i, (ax, colour) in enumerate(zip(axs, colours)):
    # Use fancy indexing to plot data in each state.
    mask = hidden_states == i
    ax.plot_date(dates[mask], close_v[mask], ".-", c=colour)
    ax.set_title("{0}th hidden state".format(i))

    # Format the ticks.
    ax.xaxis.set_major_locator(YearLocator())
    ax.xaxis.set_minor_locator(MonthLocator())

    ax.grid(True)

plt.show()

Transition matrix
[[  9.79216856e-01   1.80619536e-02   2.72119014e-03   4.23267085e-15]
 [  1.18979165e-01   4.60956465e-01   1.78117670e-18   4.20064369e-01]
 [  3.25234925e-03   6.91954277e-04   8.83415101e-01   1.12640595e-01]
 [  1.49619660e-12   4.13345076e-02   1.85175084e-01   7.73490408e-01]]

Means and vars of each hidden state
0th hidden state
mean =  [  2.33400461e-02   4.97391215e+07]
var =  [  6.97669921e-01   2.49469844e+14]

1th hidden state
mean =  [ -3.54007762e-01   1.53101845e+08]
var =  [  2.55942610e+00   5.89079688e+15]

2th hidden state
mean =  [  7.69147387e-03   5.43217397e+07]
var =  [  5.02410271e-02   1.54666224e+14]

3th hidden state
mean =  [  2.12692657e-02   8.82158103e+07]
var =  [  1.18737433e-01   5.65031171e+14]

